version: '3'
services:
  db:
    image: postgres:13.6
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=todoozie_db
    ports:
      - "5432:5432"
  app:
    build: .
    environment:
      SECRET_KEY: 77b070105b32e1b78c3b16374702a634ca1349e966e2c9e4cede09154a0e048f
      DB_PASSWORD: admin
      DB_HOST: db
    depends_on:
      - db
    ports:
      - "8000:8000"
